Firefly.BoxDescriptor=function(b){Firefly.ComponentBaseDescriptor.call(this,b);var c=this;this.title="\u77e9\u5f62\u6846";var e=this.createChildren;this.createChildren=function(a){e.call(this,a);a=a.form;Firefly.FormViewManager.createHeader("\u8fb9\u6846\u8bbe\u5b9a").appendTo(a);this.borderStyleDropDown=new Firefly.Dropdown("\u6837\u5f0f",[{value:"none",label:"\u65e0\u6837\u5f0f"},{value:"solid",label:"\u5b9e\u7ebf"},{value:"double",label:"\u53cc\u7ebf"},{value:"dotted",label:"\u70b9\u5212\u7ebf"},
{value:"dashed",label:"\u865a\u7ebf"},{value:"groove",label:"\u69fd\u72b6"},{value:"ridge",label:"\u810a\u72b6"},{value:"inset",label:"\u51f9\u9677"},{value:"outset",label:"\u51f8\u51fa"}]);this.borderStyleDropDown.view.appendTo(a);var b=this.getBorderStyle();this.borderStyleDropDown.setValue(b);var d=Firefly.FormViewManager.createTextInputView("\u5bbd\u5ea6");d.appendTo(a);this.borderSizeInput=d.find("input").eq(0);this.borderSizeInput.val(this.getBorderSize());d=Firefly.FormViewManager.createColorPickerView("\u989c\u8272");
d.appendTo(a);this.borderColorPicker=new Firefly.ColorPicker(this.getBorderColor(),d.find(".colorPicker"));d=Firefly.FormViewManager.createTextInputView("\u5706\u89d2");d.appendTo(a);this.borderRadiusInput=d.find("input").eq(0);this.borderRadiusInput.val(this.getBorderRadius());this.checkBorderStyle(b);Firefly.FormViewManager.createHeader("\u80cc\u666f\u8bbe\u5b9a").appendTo(a);b=Firefly.FormViewManager.createCheckBoxView("\u900f\u660e");b.appendTo(a);this.transBackgroundCheckBox=b.find(".ui.checkbox").eq(0);
b=this.getBackgroundTransparent();this.transBackgroundCheckBox.checkbox(b?"set checked":"set unchecked");d=Firefly.FormViewManager.createColorPickerView("\u989c\u8272");d.appendTo(a);this.backgroundColorPicker=new Firefly.ColorPicker(this.getBackgroundColor(),d.find(".colorPicker"));this.checkBackgroundTransparent(b);this.borderStyleDropDown.onChange=function(a){var b=c.getBorderStyle();Firefly.HistoryManager.addPropertiesEditAction(b,a,function(a){c.setBorderStyle(a);c.borderStyleDropDown.setValue(a)})};
this.borderSizeInput.change(function(){var a=c.getBorderSize(),b=c.borderSizeInput.val();Firefly.HistoryManager.addPropertiesEditAction(a,b,function(a){c.setBorderSize(a);c.borderSizeInput.val(a)})});this.borderColorPicker.onSubmit=function(a){var b=c.getBorderColor();Firefly.HistoryManager.addPropertiesEditAction(b,a,function(a){c.setBorderColor(a);c.borderColorPicker.setColor(a)})};this.borderRadiusInput.change(function(){var a=c.getBorderRadius(),b=c.borderRadiusInput.val();Firefly.HistoryManager.addPropertiesEditAction(a,
b,function(a){c.setBorderRadius(a);c.borderRadiusInput.val(a)})});this.backgroundColorPicker.onSubmit=function(a){var b=c.getBackgroundColor();Firefly.HistoryManager.addPropertiesEditAction(b,a,function(a){c.setBackgroundColor(a);c.backgroundColorPicker.setColor(a)})};this.transBackgroundCheckBox.checkbox({onChange:function(){var a=c.getBackgroundTransparent(),b=c.transBackgroundCheckBox.checkbox("is checked");Firefly.HistoryManager.addPropertiesEditAction(a,b,function(a){c.setBackgroundTransparent(a);
c.transBackgroundCheckBox.checkbox(a?"set checked":"set unchecked")})}})};this.getBorderStyle=function(){return b.view.css("border-style")};this.checkBorderStyle=function(a){var b=this.borderSizeInput.parent().parent(),c=this.borderColorPicker.view.parent().parent(),e=this.borderRadiusInput.parent().parent();b[a!="none"?"removeClass":"addClass"]("disabled");c[a!="none"?"removeClass":"addClass"]("disabled");e[a!="none"?"removeClass":"addClass"]("disabled");this.borderSizeInput.val(this.getBorderSize());
this.borderColorPicker.setColor(this.getBorderColor());this.borderRadiusInput.val(this.getBorderRadius())};this.setBorderStyle=function(a){b.view.css("border-style",a);this.checkBorderStyle(a)};this.getBorderSize=function(){return parseInt(b.view.css("border-width"))};this.setBorderSize=function(a){b.view.css("border-width",a)};this.getBorderColor=function(){var a=b.view.css("border-color");return Firefly.Color.getCSSHexColor(a)};this.setBorderColor=function(a){b.view.css("border-color",a)};this.getBorderRadius=
function(){return parseInt(b.view.css("border-radius"))};this.setBorderRadius=function(a){b.view.css("border-radius",a+"px")};this.getBackgroundTransparent=function(){var a=b.view.css("background-color");if(a.indexOf("rgba")>-1&&(a=a.substr(5,a.length-6).split(",")[3],Number(a)==0))return!0;return!1};this.setBackgroundTransparent=function(a){b.view.css("background-color","rgba(0,0,0,0)");this.checkBackgroundTransparent(a)};this.checkBackgroundTransparent=function(a){this.backgroundColorPicker.view.parent().parent()[!a?
"removeClass":"addClass"]("disabled");this.backgroundColorPicker.setColor(this.getBackgroundColor())};this.getBackgroundColor=function(){var a=b.view.css("background-color");return Firefly.Color.getCSSHexColor(a)};this.setBackgroundColor=function(a){b.view.css("background-color",a)}};
