Firefly.LabelDescriptor=function(b){Firefly.ComponentBaseDescriptor.call(this,b);var c=this;this.title="\u5355\u884c\u6587\u672c";var d=this.createChildren;this.createChildren=function(a){d.call(this,a);var b=Firefly.FormViewManager.createTextInputView("\u6587\u5b57");b.appendTo(a.form);this.textInput=b.find("input").eq(0);b=function(){for(var a=[],b=0;b<Firefly.fontNames.length;b++)a.push({value:b,label:Firefly.fontNames[b]});return a}();this.fontDropdown=new Firefly.Dropdown("\u5b57\u4f53",b);this.fontDropdown.view.appendTo(a.form);
b=Firefly.FormViewManager.createTextInputView("\u5b57\u4f53\u5927\u5c0f");b.appendTo(a.form);this.fontSizeInput=b.find("input").eq(0);b=Firefly.FormViewManager.createTextInputView("\u5b57\u6bcd\u95f4\u9694");b.appendTo(a.form);this.letterSpacingInput=b.find("input").eq(0);b=Firefly.FormViewManager.createColorPickerView("\u6587\u5b57\u989c\u8272");b.appendTo(a.form);var e=Firefly.FormViewManager.createFontStyleView("\u6587\u5b57\u98ce\u683c");e.appendTo(a.form);this.fontStyleController=new Firefly.FontStyleController(e.find(".ui.icon.buttons"));
e=Firefly.FormViewManager.createTextHAlignView("\u6c34\u5e73\u5bf9\u9f50");e.appendTo(a.form);this.hAlignController=new Firefly.HAlignController(e.find(".ui.icon.buttons"));this.textInput.val(this.getText());this.fontDropdown.setValue(this.getFontFamily());this.fontSizeInput.val(this.getFontSize());this.letterSpacingInput.val(this.getLetterSpacing());this.fontColorPicker=new Firefly.ColorPicker(this.getFontColor(),b.find(".colorPicker"));this.fontStyleController.setValue(this.getFontStyle());this.hAlignController.setValue(this.getHAlign());
this.textInput.change(function(){var a=c.getText(),b=c.textInput.val();Firefly.HistoryManager.addPropertiesEditAction(a,b,function(a){c.setText(a);c.textInput.val(a)})});this.fontDropdown.onChange=function(a){var b=c.getFontFamily();Firefly.HistoryManager.addPropertiesEditAction(b,a,function(a){c.setFontFamily(a);c.fontDropdown.setValue(a)})};this.fontSizeInput.change(function(){var a=c.getFontSize(),b=c.fontSizeInput.val();Firefly.HistoryManager.addPropertiesEditAction(a,b,function(a){c.setFontSize(a);
c.fontSizeInput.val(a)})});this.letterSpacingInput.change(function(){var a=c.getLetterSpacing(),b=c.letterSpacingInput.val();Firefly.HistoryManager.addPropertiesEditAction(a,b,function(a){c.setLetterSpacing(a);c.letterSpacingInput.val(a)})});this.fontColorPicker.onSubmit=function(a){var b=c.getFontColor();Firefly.HistoryManager.addPropertiesEditAction(b,a,function(a){c.setFontColor(a);c.fontColorPicker.setColor(a)})};this.fontStyleController.onChange=function(a){var b=c.getFontStyle();Firefly.HistoryManager.addPropertiesEditAction(b,
a,function(a){c.setFontStyle(a);c.fontStyleController.setValue(a)})};this.hAlignController.onChange=function(a){var b=c.getHAlign();Firefly.HistoryManager.addPropertiesEditAction(b,a,function(a){c.setHAlign(a);c.hAlignController.setValue(a)})}};this.getText=function(){return b.labelView.text()};this.setText=function(a){b.setText(a);this.update();Firefly.editor.getEditorCanvas().scaleTool.update()};this.getFontFamily=function(){var a=b.labelView.css("font-family"),a=a.replace(/'/g,"");return Firefly.fontNames.indexOf(a)};
this.setFontFamily=function(a){b.setFontFamily(Firefly.fontNames[a]);this.update();Firefly.editor.getEditorCanvas().scaleTool.update()};this.getFontSize=function(){return parseInt(b.labelView.css("font-size"))};this.setFontSize=function(a){b.setFontSize(a);this.update();Firefly.editor.getEditorCanvas().scaleTool.update()};this.getLetterSpacing=function(){var a=b.labelView.css("letter-spacing");return parseInt(a)};this.setLetterSpacing=function(a){b.labelView.css("letter-spacing",a+"px");b.setText(b.labelView.text());
this.update();Firefly.editor.getEditorCanvas().scaleTool.update()};this.getFontColor=function(){var a=b.labelView.css("color");return Firefly.Color.getCSSHexColor(a)};this.setFontColor=function(a){b.labelView.css("color",a)};this.getFontStyle=function(){var a=b.labelView.css("font-weight"),c=b.labelView.css("font-style"),e=b.labelView.css("text-decoration"),f=[];f.push(a<=400?0:1);f.push(c=="italic"?1:0);f.push(e.indexOf("underline")>-1?1:0);f.push(e.indexOf("line-through")>-1?1:0);return f.join(",")};
this.setFontStyle=function(a){a=a.split(",");b.labelView.css("font-weight",a[0]=="1"?700:400);b.labelView.css("font-style",a[1]=="1"?"italic":"normal");a[2]=="1"&&a[3]=="1"?b.labelView.css("text-decoration","underline line-through"):a[2]=="1"?b.labelView.css("text-decoration","underline"):a[3]=="1"?b.labelView.css("text-decoration","line-through"):b.labelView.css("text-decoration","none");b.setText(b.labelView.text());this.update();Firefly.editor.getEditorCanvas().scaleTool.update()};this.getHAlign=
function(){return b.getHAlign()};this.setHAlign=function(a){b.setHAlign(a)}};Firefly.fontNames=["Arial","Arial Black","Arial Narrow","Verdana","Georgia","Times New Roman","Trebuchet MS","Courier New","Impact","Comic Sans MS","Tahoma","Courier","Lucida Sans Unicode","Lucida Console","Garamond","MS Sans Serif","MS Serif","Palatino Linotype"];
Firefly.FontStyleController=function(b){var c=this,d=b.find("button");d.each(function(a,b){$(b).click(function(){$(this).toggleClass("yellow basic");c.onChange(c.getValue())})});this.setValue=function(a){var b=a.split(",");d.each(function(a,c){$(c)[b[a]=="1"?"addClass":"removeClass"]("yellow basic")})};this.getValue=function(){var a=[];d.each(function(b,c){var d=$(c).hasClass("yellow basic");a.push(d?1:0)});return a.join(",")}};
Firefly.HAlignController=function(b){var c=this,d=b.find("button"),a=-1,g=["left","center","right"];d.each(function(b,d){$(d).click(function(){a!=b&&(c.selectIdx(b),c.onChange(c.getValue()))})});this.selectIdx=function(b){a>-1&&d.eq(a).removeClass("active");a=b;d.eq(b).addClass("active")};this.setValue=function(a){this.selectIdx(g.indexOf(a))};this.getValue=function(){return g[a]}};
