Firefly.ParagraphDescriptor=function(b){Firefly.ComponentBaseDescriptor.call(this,b);var c=this;this.title="\u591a\u884c\u6587\u672c";var f=this.createChildren;this.createChildren=function(a){f.call(this,a);var b=Firefly.FormViewManager.createTextAreaView("HTML\u6587\u672c");b.appendTo(a.form);this.textInput=b.find("textarea").eq(0);b=function(){for(var a=[],b=0;b<Firefly.fontNames.length;b++)a.push({value:b,label:Firefly.fontNames[b]});return a}();this.fontDropdown=new Firefly.Dropdown("\u5b57\u4f53",
b);this.fontDropdown.view.appendTo(a.form);b=Firefly.FormViewManager.createTextInputView("\u5b57\u4f53\u5927\u5c0f");b.appendTo(a.form);this.fontSizeInput=b.find("input").eq(0);b=Firefly.FormViewManager.createTextInputView("\u5b57\u6bcd\u95f4\u9694");b.appendTo(a.form);this.letterSpacingInput=b.find("input").eq(0);b=Firefly.FormViewManager.createTextInputWithRightLabelView("\u884c\u8ddd","em");b.appendTo(a.form);this.lineHeightInput=b.find("input").eq(0);b=Firefly.FormViewManager.createColorPickerView("\u6587\u5b57\u989c\u8272");
b.appendTo(a.form);var d=Firefly.FormViewManager.createFontStyleView("\u6587\u5b57\u98ce\u683c");d.appendTo(a.form);this.fontStyleController=new Firefly.FontStyleController(d.find(".ui.icon.buttons"));d=Firefly.FormViewManager.createTextHAlignView("\u6c34\u5e73\u5bf9\u9f50");d.appendTo(a.form);this.hAlignController=new Firefly.HAlignController(d.find(".ui.icon.buttons"));this.overflowDropdown=new Firefly.Dropdown("\u6587\u672c\u6ea2\u51fa",[{value:"auto",label:"\u81ea\u52a8"},{value:"hidden",label:"\u9690\u85cf"}]);
this.overflowDropdown.view.appendTo(a.form);d=Firefly.FormViewManager.createCheckBoxView("\u663e\u793a\u8fb9\u6846");d.appendTo(a.form);this.showBorderCheckBox=d.find(".ui.checkbox").eq(0);this.textInput.val(this.getText());this.fontDropdown.setValue(this.getFontFamily());this.fontSizeInput.val(this.getFontSize());this.letterSpacingInput.val(this.getLetterSpacing());this.lineHeightInput.val(this.getLineHeight());this.fontColorPicker=new Firefly.ColorPicker(this.getFontColor(),b.find(".colorPicker"));
this.fontStyleController.setValue(this.getFontStyle());this.hAlignController.setValue(this.getHAlign());this.overflowDropdown.setValue(this.getOverflow());this.showBorderCheckBox.checkbox(this.getShowBorder()?"set checked":"set unchecked");this.textInput.change(function(){var a=c.getText(),b=c.textInput.val();Firefly.HistoryManager.addPropertiesEditAction(a,b,function(a){c.setText(a);c.textInput.val(a)})});this.fontDropdown.onChange=function(a){var b=c.getFontFamily();Firefly.HistoryManager.addPropertiesEditAction(b,
a,function(a){c.setFontFamily(a);c.fontDropdown.setValue(a)})};this.fontSizeInput.change(function(){var a=c.getFontSize(),b=c.fontSizeInput.val();Firefly.HistoryManager.addPropertiesEditAction(a,b,function(a){c.setFontSize(a);c.fontSizeInput.val(a)})});this.letterSpacingInput.change(function(){var a=c.getLetterSpacing(),b=c.letterSpacingInput.val();Firefly.HistoryManager.addPropertiesEditAction(a,b,function(a){c.setLetterSpacing(a);c.letterSpacingInput.val(a)})});this.lineHeightInput.change(function(){var a=
c.getLineHeight(),b=c.lineHeightInput.val();Firefly.HistoryManager.addPropertiesEditAction(a,b,function(a){c.setLineHeight(a);c.lineHeightInput.val(a)})});this.fontColorPicker.onSubmit=function(a){var b=c.getFontColor();Firefly.HistoryManager.addPropertiesEditAction(b,a,function(a){c.setFontColor(a);c.fontColorPicker.setColor(a)})};this.fontStyleController.onChange=function(a){var b=c.getFontStyle();Firefly.HistoryManager.addPropertiesEditAction(b,a,function(a){c.setFontStyle(a);c.fontStyleController.setValue(a)})};
this.hAlignController.onChange=function(a){var b=c.getHAlign();Firefly.HistoryManager.addPropertiesEditAction(b,a,function(a){c.setHAlign(a);c.hAlignController.setValue(a)})};this.overflowDropdown.onChange=function(a){var b=c.getOverflow();Firefly.HistoryManager.addPropertiesEditAction(b,a,function(a){c.setOverflow(a);c.overflowDropdown.setValue(a)})};this.showBorderCheckBox.checkbox({onChange:function(){var a=c.getShowBorder(),b=c.showBorderCheckBox.checkbox("is checked");Firefly.HistoryManager.addPropertiesEditAction(a,
b,function(a){c.setShowBorder(a);c.showBorderCheckBox.checkbox(a?"set checked":"set unchecked")})}})};this.getText=function(){return b.textView.html()};this.setText=function(a){b.setText(a)};this.getFontFamily=function(){var a=b.textView.css("font-family"),a=a.replace(/'/g,"");return Firefly.fontNames.indexOf(a)};this.setFontFamily=function(a){b.textView.css("font-family",Firefly.fontNames[a])};this.getFontSize=function(){return parseInt(b.textView.css("font-size"))};this.setFontSize=function(a){b.textView.css("font-size",
a+"px");this.setLineHeight(this.lineHeightInput.val())};this.getLetterSpacing=function(){var a=b.textView.css("letter-spacing");return parseInt(a)};this.setLetterSpacing=function(a){b.textView.css("letter-spacing",a+"px")};this.getLineHeight=function(){var a=parseInt(b.textView.css("line-height"))/this.getFontSize();return a=Math.round(a*100)/100};this.setLineHeight=function(a){b.textView.css("line-height",a+"em")};this.getFontColor=function(){var a=b.textView.css("color");return Firefly.Color.getCSSHexColor(a)};
this.setFontColor=function(a){b.textView.css("color",a)};this.getFontStyle=function(){var a=b.textView.css("font-weight"),c=b.textView.css("font-style"),d=b.textView.css("text-decoration"),e=[];e.push(a<=400?0:1);e.push(c=="italic"?1:0);e.push(d.indexOf("underline")>-1?1:0);e.push(d.indexOf("line-through")>-1?1:0);return e.join(",")};this.setFontStyle=function(a){a=a.split(",");b.textView.css("font-weight",a[0]=="1"?700:400);b.textView.css("font-style",a[1]=="1"?"italic":"normal");a[2]=="1"&&a[3]==
"1"?b.textView.css("text-decoration","underline line-through"):a[2]=="1"?b.textView.css("text-decoration","underline"):a[3]=="1"?b.textView.css("text-decoration","line-through"):b.textView.css("text-decoration","none")};this.getHAlign=function(){return b.textView.css("text-align")};this.setHAlign=function(a){b.textView.css("text-align",a)};this.getOverflow=function(){return b.view.css("overflow")};this.setOverflow=function(a){b.view.css("overflow",a)};this.getShowBorder=function(){return b.view.css("border").indexOf("none")>
-1?!1:!0};this.setShowBorder=function(a){b.view.css("border",a?"solid 1px":"none")}};
